### PR TITLE
pw/Create Welcome-to-Voucherify.md

### PR DESCRIPTION
**Pull request by p-woznikowski**
Working on this task: [Welcome to Voucherify](https://3.basecamp.com/3108604/buckets/34857884/todos/6692958743)

### CODE REVIEW

**Comment by p-woznikowski** [comment]
Final version of the Welcome to Voucherify article
- Added 2 images
- Updated [Stackable Discounts API](https://docs.voucherify.io/docs/manage-stackable-discounts) article
- Updated changelog

**Review by p-zielinski — CHANGES_REQUESTED** [review]
As we have spoken.
Please include information that is missing in docs/guides/discounts_recipes/Stackable-Discounts-API.md

**Comment by p-woznikowski** [comment]
@p-zielinski, I've changed the Stackable Discounts API article

Feel free to proceed

**Review by p-zielinski — APPROVED** [review]
Please next time provide link to test documentation, such as https://docs.voucherify.io/v2018-08-01-pw-511/docs/manage-stackable-discounts

**Pull request merged**
